---
author: Jotschi
author_email: webmaster@jotschi.de
author_login: admin
author_url: http://www.Jotschi.de
categories:
- Technik
comments: []
date: 2009-05-19T20:33:46Z
excerpt: "I finally managed to get fglrx working with dri and dual head using the
  latest ati driver: \nati-driver-installer-9-4-x86.x86_64.run\n\n_Update:_\nworks
  also with:\nati-driver-installer-9-5-x86.x86_64.run\n"
published: true
status: publish
tags:
- debian
- xorg.conf
- linux
- ati
- fglrx
title: fglrx and Debian testing on amd64 - 2.6.26-2-amd64
url: /2009/05/19/fglrx-and-debian-testing-on-amd64-2626-2-amd64/
wordpress_id: 269
wordpress_url: /?p=269
---

I finally managed to get fglrx working with dri and dual head using the latest ati driver: 
ati-driver-installer-9-4-x86.x86_64.run

_Update:_
works also with:
ati-driver-installer-9-5-x86.x86_64.run

<a id="more"></a><a id="more-269"></a>
Some Notes:


----
jotschi@NeXuS:~$ uname -r
2.6.26-2-amd64

jotschi@NeXuS:~$ fglrxinfo 
display: :0.0  screen: 0
OpenGL vendor string: ATI Technologies Inc.
OpenGL renderer string: ATI Radeon HD 4800 Series
OpenGL version string: 2.1.8591

jotschi@NeXuS:~/Desktop$ dpkg -l | grep fglrx
ii  fglrx-amdcccle                     8.602-1                     Catalyst Control Center for the ATI graphics accelerators
ii  fglrx-driver                            8.602-1                     Video driver for the ATI graphics accelerators
ii  fglrx-driver-dev                      8.602-1                     Video driver for the ATI graphics accelerators (devel files)
ii  fglrx-kernel-2.6.26-2-amd64   8.602-1+2.6.26-15           ATI binary kernel module for Linux 2.6.26-2-amd64
ii  fglrx-kernel-src                     8.602-1                     Kernel module source for the ATI graphics accelerators

jotschi@NeXuS:~/Desktop$ dpkg -l | grep xorg | head -n 4 | grep -v docs
ii  xorg                                    1:7.3+18                    X.Org X Window System
ii  xserver-xorg                         1:7.3+18                    the X.Org X server
ii  xserver-xorg-core                  2:1.4.2-11                  Xorg X server - core server
----


Mainly i used this guide: <a href="http://wiki.cchtml.com/index.php/Debian_Installation_Guide">http://wiki.cchtml.com/index.php/Debian_Installation_Guide</a>

There were some glitches because of missing files and creation of diverations. I belive the uninstallation of fglrx does not revert created diverations of certain libraries. (I dunno if the removeal of created diverations this is the expected behaviour of package removeal)

My short Howto:
0. Optional: 
I removed non-free from my source.lst and did an apt-get update and apt-get clean to make sure that the module assistent would not fetch some fglrx packages via network.

1. Stop X

2. unload fglrx module
----
modprobe -r fglrx 
----

3. Install additional packages you might need:
----
apt-get install module-assistant build-essential fakeroot dh-make debconf bzip2 wget libstdc++5 ia32-libs
apt-get install kernel-headers-$(uname -r)
----

4. Remove all fglrx packages. You might have to change the order of command due to dependencies between the packages.
<code>dpkg -l | grep fglrx
dpkg -P  fglrx-amdcccle 
dpkg -P fglrx-driver-dev 
dpkg -P fglrx-kernel-src
dpkg -P fglrx-kernel-2.6.26-2-amd64
dpkg -P fglrx-driver</code>    

5. To restore the files that might have been deleted by the fglrx package removeal routines you can use:
----
apt-get --reinstall install libgl1-mesa-glx
apt-get --reinstall install xserver-xorg-core
apt-get --reinstall install ia32-libs
----

6. Create the fglrx packages:
----
./ati-driver-installer-9-4-x86.x86_64.run --extract fglrx_9-4
cd fglrx_9-4
cd arch/x86_64/usr/X11R6
ln -s lib64 lib
cd ../../..
./packages/Debian/ati-packager.sh --buildpkg testing
cd ..
----

7. Remove leftovers of previous installations:
----
rm /usr/src/fglrx.tar.bz2
rm /usr/src/*fglrx*.deb
----

8. Install the packages. You might have to change the order due to dependencies.
----
dpkg -i fglrx-driver_8.602-1_amd64.deb
dpkg -i fglrx-amdcccle_8.602-1_amd64.deb
dpkg -i fglrx-driver-dev_8.602-1_amd64.deb
dpkg -i fglrx-kernel-src_8.602-1_amd64.deb
----

_Note: diversion problem_
I got some nasty failure while installing fglrx-driver_8.602-1_amd64.deb
The package installation script was complaining about a failure while creating a diversion of libGL.so.1.2 because that file was used by the package xserver-xorg-core.
The installation terminated with:
<code>dpkg: error processing xorg-driver-fglrx</code>
You can get rid of those failures by using the <a href="http://www.debian.org/distrib/packages">Debian Package Search</a>. Use the last form of the page to locate the file (e.g. libGL.so.1.2)
As you see the file /usr/lib/libGL.so.1.2 is part of fglrx and the package libgl1-mesa-glx. I just reinstalled libgl1-mesa-glx and fixed the bug. <del datetime="2009-05-19T21:01:33+00:00">You may also remove the package because you wont need mesa once using hardware acceleration. (Please correct me if this is wrong - I'm not quite sure about this)
</del>

----
(Reading database ... 84741 files and directories currently installed.)
Unpacking fglrx-driver (from fglrx-driver_8.612-1_amd64.deb) ...
No diversion `diversion of /usr/lib/libGL.so.1.2 to /usr/share/fglrx/diversions/libGL.so.1.2 by fglrx-driver', none removed
Adding `diversion of /usr/lib/libGL.so.1.2 to /usr/lib/fglrx/diversions/libGL.so.1.2 by fglrx-driver'
Adding `diversion of /usr/lib/libGL.so.1 to /usr/lib/fglrx/diversions/libGL.so.1 by fglrx-driver'
No diversion `diversion of /emul/ia32-linux/usr/lib/libGL.so.1.2 to /usr/share/fglrx/diversions/libGL.so.1.2_32bit by fglrx-driver', none removed
Adding `diversion of /emul/ia32-linux/usr/lib/libGL.so.1.2 to /emul/ia32-linux/usr/lib/fglrx/diversions/libGL.so.1.2 by fglrx-driver'
Adding `diversion of /emul/ia32-linux/usr/lib/libGL.so.1 to /emul/ia32-linux/usr/lib/fglrx/diversions/libGL.so.1 by fglrx-driver'
rmdir: failed to remove `/usr/share/fglrx/diversions': No such file or directory
rmdir: failed to remove `/usr/share/fglrx': No such file or directory
Leaving `diversion of /usr/lib/libGL.so.1.2 to /usr/lib/fglrx/diversions/libGL.so.1.2 by fglrx-driver'
Leaving `diversion of /usr/lib/libGL.so.1 to /usr/lib/fglrx/diversions/libGL.so.1 by fglrx-driver'
Leaving `diversion of /emul/ia32-linux/usr/lib/libGL.so.1.2 to /emul/ia32-linux/usr/lib/fglrx/diversions/libGL.so.1.2 by fglrx-driver'
Leaving `diversion of /emul/ia32-linux/usr/lib/libGL.so.1 to /emul/ia32-linux/usr/lib/fglrx/diversions/libGL.so.1 by fglrx-driver'
Adding `diversion of /usr/lib/xorg/modules/extensions/libdri.so to /usr/lib/fglrx/diversions/libdri.so by fglrx-driver'
dpkg - warning, overriding problem because --force enabled:
_ trying to overwrite `/usr/lib/xorg/modules/extensions/libglx.so', which is also in package xserver-xorg-core_
dpkg: error processing 1 (--install):
 cannot access archive: No such file or directory
Setting up fglrx-driver (8.612-1) ...

Configuration file `/etc/acpi/fglrx-powermode.sh', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/acpi/events/fglrx-lid-aticonfig', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/acpi/events/fglrx-ac-aticonfig', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/init.d/atieventsd', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/default/fglrx', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/ati/logo_mask.xbm.example', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/ati/signature', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/ati/control', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/ati/atiogl.xml', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/ati/amdpcsdb.default', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/ati/logo.xbm.example', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/ati/authatieventsd.sh', does not exist on system.
Installing new config file as you request.

Configuration file `/etc/X11/Xsession.d/70fglrx', does not exist on system.
Installing new config file as you request.
update-rc.d: warning: /etc/init.d/atieventsd missing LSB information
update-rc.d: see <http://wiki.debian.org/LSBInitScripts>
Starting atieventsd: /usr/sbin/atieventsd already running.
done.
Processing triggers for man-db ...
Errors were encountered while processing:
 1
----

Once you get only the following error you can proceed with dpkg --force-all:
_trying to overwrite `/usr/lib/xorg/modules/extensions/libglx.so’, which is also in package xserver-xorg-core_

Finally i had to use the --force-all option to install the package. 
----
dpkg --force-all -i fglrx-driver_8.602-1_amd64.deb
----

_You should try to use the procedure described above before taking this quite drastic step. _

9. Build and install the fglrx kernel module. I had not to modify the sources in any way.
----
module-assistant auto-install fglrx-kernel-src
----

10. Load the module:
----
modprobe fglrx
----

11. Make sure it was loaded. If it wasn't loaded use dmesg to check what happed.
----
lsmod | grep fglrx
----

12. If you want to create a new xorg.conf file which stores your monitor setup etc.:
----
mv /etc/X11/xorg.conf /etc/X11/xorg.conf.backup
dpkg-reconfigure xserver-xorg (just follow the instructions)
aticonfig --initial
----

13. You are done. Now start X and run the amdcccle tool and setup your screens. I had to run those steps to get dual head working:
* Enable both displays using amdcccle
* Set the resolution of both displays to the same one
* Enabling Xinerama
* Restart X
* Enabling Multi-Display Settings (Left of ..)
* Restart X
* Disabling Xinerama in /etc/X11/xorg.conf 
* Restart X

Download my xorg.conf:
<a href='/downloads/xorg/xorg.conf'>xorg.conf</a>

Overall this is a painstaking way of setting up dual head display and drivers. Please AMD / ATI create an Installer that creates valid Deb. packages or even better delete it and create a deb repository that everybody can use.

