---
author: Jotschi
author_email: webmaster@jotschi.de
author_login: admin
author_url: http://www.Jotschi.de
categories:
- Technik
- GFX
comments: []
date: 2007-03-05T02:35:52Z
excerpt: "Demis_Maps ist ein kleines Java Tool um Demis Maps mithilfe einer KMZ/KML
  von Google Earth fÃ\x83Â¼r TTMM aufzubereiten.\r\n"
published: true
status: publish
tags: []
title: Demis Maps Java Tool
url: /2007/03/05/demis-maps-java-tool/
wordpress_id: 84
wordpress_url: /?p=84
---

Demis_Maps ist ein kleines Java Tool um Demis Maps mithilfe einer KMZ/KML von Google Earth für TTMM aufzubereiten.

TTMM  (Tom Tom Moving Map) ist ein TomTom Plugin zum darstellen von Rasterkarten. Somit ist es möglich irgendwelche Karten die man selbst erstellt hat innerhalb von TomTom zu verwenden. Es ist sogar möglich Google Earth mittels Tomtom und TTMM auf einem PocketPC zu simulieren. Dies ist jedoch je nach Umfang mit enormem Aufwand verbunden. 
Demis Maps sind jedoch keine Satellitenbilder sondern eher Topografische Karten.

Durch die KMZ/KML aus Google Earth ist es möglich einen Bereich zu definieren dieser Bereich wird in einzelnen Teilkarten herruntergeladen um so eine relativ höhere Auflösung zu erreichen.

Unter demis.nl kann man einen Blick auf die möglichen Kartenvarienten werfen.

Anleitung:

1. Zipfile irgendwohin entpacken

2. Google Earth starten und dort ein Bildoverlay hinzufügen. (irgendein Bild wählen)
Das Bildoverlay dient nur dazu das demis_maps weiß welchen Bereich es später herrunterladen soll.
Dieses Overlay im Ordner wo sich demis_maps befindet abspeichern.

3. Mittels Console in jenes Verzeichnis wechseln.

4. Befehl ausführen: java -classpath X:\xyz\demis_maps demis_fetch

(Pfad bitte anpassen)
(Java 1.5 oder höher empfolen)
(Evtl. Einstellungen vornehmen)

oder

[source, bash]
----
java -classpath X:\xyz\demis_maps demis_fetch export.kmz
(export.kmz ist das exportierte Bildoverlay)
----

5. demis_maps erstellt einen Ordner (default: demis_slice). In diesem Ordner befindet sich nun bei default settings eine kml-Datei. Diese lässt sich per Drag and Drop in Google Earth ziehen bzw. importieren. Das Ergebnis sollte direkt sichtbar sein.

Die einzelnen Teile lassen sich nun je nach bedarf exportieren und für TTMM verwenden.
Schritt 5 kann auch übersprungen werden wenn man mit "-f false" start.
Dadurch werden die einzelnen Overlays nicht in einem Ordner gespeichert sondern in einzelnen kml Dateien.

Vielleicht kann jemand es ja gebrauchen. Ich finde es praktisch weil ich so die Bahnwege abspeichern kann. 


Download: link:/downloads/demis/demis_maps.zip[Demis Maps]
Link: http://forum.pocketnavigation.de/thread.php?threadid=1026055&threadview=0&hilight=&hilightuser=0&sid=482ddaa19c4e1965e94ba18eb6f41169&page=1[TTMM]
