---
author: Jotschi
author_email: webmaster@jotschi.de
author_login: admin
author_url: http://www.Jotschi.de
categories:
- Technik
- GFX
comments:
- author: Sam
  author_email: og_sam@hotmail.com
  author_url: ""
  content: |-
    To 1: It depends on your texture setting (clamp, repeat etc.)
    But normally (without touching the texture matrix), you would
    use unity TexCoords (0.0 - 1.0) per component.
    Furthermore, texture lookups are expensive. If you just want the alpha value and later the whole texel as fragment color: store it in a vec4 instead of reading it twice.

    2. Take a look at textureSize (returns an ivec) and the minimum GLSL version.

    3. Why not? But if you don't use light sources, the gl_LightSource array isn't active and therefore doesn't eat up memory or something.
    It behaves the opposite way: gl_LightSource contains more than just a position (attenuation and all those parameters).
    You wand an uniform array of vec3's ? Then just implement that.
    In new GLSl specs, you do not even have those default uniforms,
    you have to define them yourself, as you did. Keep this approach up.




        float dx = projectPos[i].x - glPos.x;
      float dy = projectPos[i].y - glPos.y;
      float dz = projectPos[i].z - glPos.z;
      float d = Math.sqrt(dx * dx + dy * dy + dz * dz);


    I'd implement vector things using builtin vector functions.

    What you do is calculating length ^ 2 and its square root (length). The result is a scalar with an absolute value.
    In GLSlang, you can do:

    float d = length(projectPos - glPos);

    even better:

    float d = distance(projectPos,glPos);

    What if you use a vec4 and a vec3? Use zwizzles, i.E.

    float d = distance(projectPos.xyz,glPos.xyz);

    On top of less code, this distance operation is most likely implemented in hardware =&gt; calculation time per fragment decreases.


    if (alpha != 1.0f) {

    I guess you think of alpha as transparency,
    but alpha (with regard to its value) is actually opacity;
    thich means that if alpha is &gt; 0.0, the texel is "visible"

    Sam
  date: 2010-03-31 11:31:23 +0000
  date_gmt: 2010-03-31 09:31:23 +0000
  id: 1416
- author: Jotschi
  author_email: webmaster@jotschi.de
  author_url: http://www.jotschi.de
  content: "Thank you for your input Sam! \n\nI'll look into that soon when i finish
    my scene graph datastructure for my project."
  date: 2010-03-31 18:48:29 +0000
  date_gmt: 2010-03-31 16:48:29 +0000
  id: 1417
date: 2009-08-17T23:20:56Z
excerpt: 'For my project <a href="http://www.jotschi.de/?page_id=320">Generating City
  Models By Using Panorama Images</a> i have to write a fragment shader that handles
  multiple projections onto the same surface. The shader must contain condition in
  which the projection should be handled. In my case i had to decide which projection
  source should be used to texture the desired model. '
published: true
status: publish
tags:
- GLSL
- Shader
- OpenGL
title: GLSL shader to handle multiple projections onto the same surface
url: /2009/08/17/glsl-shader-to-handle-multiple-projections-onto-the-same-surface/
wordpress_id: 363
wordpress_url: /?p=363
---

For my project <a href="http://www.jotschi.de/?page_id=320">Generating City Models By Using Panorama Images</a> i have to write a fragment shader that handles multiple projections onto the same surface. The shader must contain condition in which the projection should be handled. In my case i had to decide which projection source should be used to texture the desired model. <a id="more"></a><a id="more-363"></a>
I didn't want to do alpha blending of each texture. I wanted that only the projection source will be used that would produce the best projection image. For a good projection the angle of which the projection 'light' falls onto the surface must be very low. The second parameter is the distance. 

For example, imagine a scene with 20 projection sources. One source is very near the target surface but the angle in which the 'light' falls onto the surface is very big so the texture produced by such a source wouldn't be that good. Instead there is another projection source which's projections angle is very low but the distance is larger than that of the near source. My shader will now pick the second projection source because the first does not match its condtions.

Draft of my target shader:

[source, c]
----
uniform int nTextures;
uniform sampler2DArray textures;
uniform vec3[] projectPos;
varying vec3 glPos;
varying vec3 normalVec;
void main() {
  int currentTexture=0;
  float minAngle = 360.0f;
  float angleThreshold = 10.0f;
 // Select the texture with the lowest angle
  for(int i =0; i <nTextures; i++){
   float alpha = texture2DArray(textures,vec3(gl_TexCoord[0].xy, i)).a;
   if(alpha != 1.0f) {
     //TODO check calculation of projDirection
      vec3 projDirection =(projectPos-glPos);
      float angle = dot(normalVec,projDirection*-1);
      if(angle<minAngle) {
          minAngle = angle;
      }
    }
  }
  float minDistance= -1.0f;
  // Select the texture with the lowest distance among those around the lowest angle
  for(i=0; i <nTextures; i++){
   float alpha = texture2DArray(textures,vec3(gl_TexCoord[0].xy, i)).a;
   // Condition 1: Must be visible
   if (alpha != 1.0f) {
     //TODO check calculation of projDirection
     vec3 projDirection =( projectPos-glPos);
     float angle = dot(normalVec,projDirection);
     // Condition 2: The angle must be between +-10.0f of the lowest angle
     if(angle<(minAngle+angleThreshold) || angle>(minAngle+angleThreshold)) {
     // TODO check calculation of distance between both points within R³
    float dx = projectPos[i].x - glPos.x;
  float dy = projectPos[i].y - glPos.y;
  float dz = projectPos[i].z - glPos.z;
  float d = Math.sqrt(dx * dx + dy * dy + dz * dz);
    // select the texture with the lowest distance
    if(d<minDistance || minDistance  ==-1.0f)  {
          minDistance = d;
          currentTexture = i;
    }
        }
   }
  }
gl_FragColor = texture2DArray(textures,vec3(gl_TexCoord[0].xy, currentTexture));
}
----

1. Maybe there is a better way to check if the given sample contains a texture value at the given texture coordinate than checking its alpha value.
2. I use a uniform to handle the size of the sampler2DArray textures array. Maybe you can extract that information within the shader
3. I use uniform vec3[] projectPos; to handle over the positions of the projection sources. Maybe this can be stored in the build in gl_LightSource array?
