---
author: Jotschi
author_email: webmaster@jotschi.de
author_login: admin
author_url: http://www.Jotschi.de
categories:
- Uncategorized
comments:
- author: Julien Gouesse
  author_email: gouessej@orange.fr
  author_url: http://gouessej.wordpress.com
  content: Hi. You don't need to load the native libraries by yourself especially
    since the release candidate 4 of JOGL already does it automatically when the JARs
    containing them are in the proper directory. Please avoid complicating things
    and confusing your potential readers. However, your Maven stuffs are fine. Best
    regards.
  date: 2011-10-24 13:06:14 +0000
  date_gmt: 2011-10-24 11:06:14 +0000
  id: 3397
- author: Jotschi
  author_email: webmaster@jotschi.de
  author_url: http://www.jotschi.de
  content: "Hi Julien, \n\nthanks for the input. I did not know that the RC4 will
    support loading of native libraries. Unfortunately i can't find a RC4 release
    or RC4 git tag to take a look at the loading mechanism. Could you provide any
    details on that topic so that i can update the post.\n\nThank you\n\nJotschi"
  date: 2011-10-24 17:09:56 +0000
  date_gmt: 2011-10-24 15:09:56 +0000
  id: 3398
date: 2011-09-26T23:17:02Z
excerpt: |
  _Update:_
  The upcoming RC4 of JOGL2 will support loading of native libraries. I'll update this post as soon as i get time to take a look the new loading mechanism.
  <br>

  Usually native libraries are loaded by adding the system property java.library.path to the jvm arguments. Its also possible to change the java.library.path within a static block at runtime as described <a href="http://fahdshariff.blogspot.com/2011/08/changing-java-library-path-at-runtime.html">here</a>. It's also possible to dynamically load the native libraries at runtime using the System.load method. I just wrote a small ClassPathLoader class that can be handed over to the JNILibLoaderBase class that is dealing with the loading of libraries.
published: true
status: publish
tags:
- jogl2
- native library
- classpath
title: JOGL2 (jogamp) ClassPathLoader For Native Libraries
url: /2011/09/26/jogl2-jogamp-classpathloader-for-native-libraries/
wordpress_id: 660
wordpress_url: /?p=660
---

_Update:_

The upcoming RC4 of JOGL2 will support loading of native libraries. I'll update this post as soon as i get time to take a look the new loading mechanism.

Usually native libraries are loaded by adding the system property java.library.path to the jvm arguments. 
Its also possible to change the java.library.path within a static block at runtime as described http://fahdshariff.blogspot.com/2011/08/changing-java-library-path-at-runtime.html[here].
It's also possible to dynamically load the native libraries at runtime using the System.load method.
I just wrote a small ClassPathLoader class that can be handed over to the JNILibLoaderBase class that is dealing with the loading of libraries. 

The ClassPathLoader will allow extraction of the the native libraries from jars that contain all libraries. 
For jogl2 these jars are jogl-natives-linux-i586.jar and gluegen-rt-natives-linux-i586.jar for linux-i586.
This static block can be embedded within your main class. It will disable the default loading mechanism and replace it with the classpath loader. 
Please note that is required that the native lib jars must be added to the classpath.

[source, java]
----
static {
		ClassPathLoader loader = new ClassPathLoader();
		loader.loadLibrary("gluegen-rt", true);
		JNILibLoaderBase.setLoadingAction(loader);
		NativeLibLoader.disableLoading();
	}
----

Here is the ClassPathLoader itself. No real magic here as well. Please note that the loader currently only works with linux libraries (*.so). Adaption for windows libraries (*.dll) shouldn't be that hard.

[source, java]
----
package de.jotschi.jogl2.example;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;

import com.jogamp.common.jvm.JNILibLoaderBase.LoaderAction;

public class ClassPathLoader implements LoaderAction {

	/**
	 * Loads the given library with the libname from the classpath root
	 */
	public boolean loadLibrary(String libname, boolean ignoreError) {
		String filename = "lib" + libname + ".so";
		InputStream ins = ClassLoader.getSystemResourceAsStream(filename);
		
		try {
			File tmpFile = writeTmpFile(ins, filename);
			System.load(tmpFile.getAbsolutePath());
			tmpFile.delete();
		} catch (IOException e) {
			e.printStackTrace();
			return false;
		}

		return true;
	}

	/**
	 * Write the content of the inputstream into a tempfile with the given
	 * filename
	 * 
	 * @param ins
	 * @param filename
	 * @throws IOException
	 */
	private File writeTmpFile(InputStream ins, String filename)
			throws IOException {

		File tmpFile = new File(System.getProperty("java.io.tmpdir"), filename);
		tmpFile.delete();
		FileOutputStream fos = null;
		try {
			fos = new FileOutputStream(tmpFile);

			byte[] buffer = new byte[1024];
			int len;
			while ((len = ins.read(buffer)) != -1) {

				fos.write(buffer, 0, len);
			}
		} finally {
			if (ins != null) {
				ins.close();
			}
			if (fos != null) {
				fos.close();
			}
		}
		return tmpFile;
	}

	public void loadLibrary(String libname, String[] preload,
			boolean preloadIgnoreError) {
		loadLibrary(libname, preloadIgnoreError);
	}

}
----